"""movies table

Revision ID: 48dc55069f17
Revises:
Create Date: 2023-12-08 12:03:29.503128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48dc55069f17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("rating", sa.Float(precision=3), nullable=True),
        sa.Column("review", sa.String(length=500), nullable=True),
        sa.Column("img_url", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie")
    # ### end Alembic commands ###
